import { FoodItem } from '@/types';

export const menuItemImage = (id: string) => `/uploads/menu/${id}.jpg`;
export const categoryImage = (id: string) => `/uploads/menu/categories/${id}.jpg`;

export const BRAND_NAME = 'Al-Quds';
export const BRAND_TAGLINE = 'Fried · Burgers · Arabian · Chinese · Pasta';
export const BRAND_DESCRIPTION =
  'Signature burgers, Arabian platters, Chinese, fried chicken & pasta. Order now for delivery or pickup.';

// Category colors from menu design: orange-yellow (Burgers/Arabian), teal (Chinese), purple (Pasta), Fried with brand gold
export const CATEGORY_COLORS: Record<string, string> = {
  burgers: '#D1AB66',
  arabian: '#FFB347',
  chinese: '#2EC4B6',
  fried: '#E84855',
  pasta: '#9B5DE5',
  fries: '#E8A820',
  drinks: '#3A9AD9',
};

export const CATEGORIES = [
  { id: 'all', label: 'All', icon: '🍽️' },
  { id: 'burgers', label: 'Burgers', icon: '🍔', image: '/uploads/menu/categories/burgers.jpg' },
  { id: 'arabian', label: 'Arabian', icon: '🥙', image: '/uploads/menu/categories/arabian.jpg' },
  { id: 'chinese', label: 'Chinese', icon: '🍜', image: '/uploads/menu/categories/chinese.jpg' },
  { id: 'fried', label: 'Fried', icon: '🍗', image: '/uploads/menu/categories/fried.jpg' },
  { id: 'pasta', label: 'Pasta', icon: '🍝', image: '/uploads/menu/categories/pasta.jpg' },
  { id: 'fries', label: 'Fries', icon: '🍟', image: '/uploads/menu/categories/fries.jpg' },
  { id: 'drinks', label: 'Drinks', icon: '🥤', image: '/uploads/menu/categories/drinks.jpg' },
] as const;

export const MENU_ITEMS: FoodItem[] = [
  // BURGERS
  {
    id: 'b1',
    name: 'Cocain Signature',
    description: 'Buttered bun, minced patty & chunks with cheese & jalapeno mushroom sauce.',
    price: 1099,
    category: 'burgers',
    image: '/uploads/menu/b1.jpg',
    rating: 4.9,
    prepTime: 18,
  },
  {
    id: 'b2',
    name: 'Addiction Signature',
    description: 'Buttered bun, buffalo steak with cheese sprinkle smoky onion.',
    price: 849,
    category: 'burgers',
    image: '/uploads/menu/b2.jpg',
    rating: 4.8,
    prepTime: 16,
  },
  {
    id: 'b3',
    name: 'Chicken Zinger Tower Signature',
    description: 'Buttered bun, chicken fried super classic, cheese fully loaded with white sauce.',
    price: 649,
    category: 'burgers',
    image: '/uploads/menu/b3.jpg',
    rating: 4.8,
    prepTime: 14,
  },
  {
    id: 'b4',
    name: 'Snacher Signature',
    description: 'Buttered bun, buffalo beef steak with cheese & mushroom sauce.',
    price: 999,
    category: 'burgers',
    image: '/uploads/menu/b4.jpg',
    rating: 4.9,
    prepTime: 18,
  },
  {
    id: 'b5',
    name: 'Chicken Smash 1 Patty',
    description: 'Buttered bun, chicken smash patty with regular sauce.',
    price: 349,
    category: 'burgers',
    image: '/uploads/menu/b5.jpg',
    rating: 4.6,
    prepTime: 10,
  },
  {
    id: 'b6',
    name: 'Mount Everest Signature',
    description: 'Soft long bun, grilled buffalo cheese with hot sauce & cucumber.',
    price: 1099,
    category: 'burgers',
    image: '/uploads/menu/b6.jpg',
    rating: 4.9,
    prepTime: 18,
  },
  {
    id: 'b7',
    name: 'Marijuana Signature',
    description: 'Buttered bun, chicken steak cheese, butter with mushroom sauce.',
    price: 699,
    category: 'burgers',
    image: '/uploads/menu/b7.jpg',
    rating: 4.7,
    prepTime: 14,
  },
  {
    id: 'b8',
    name: 'Capture Single Patty',
    description: 'Beef smash Bar B.Q grilled, cheese with cocktail sauce.',
    price: 599,
    category: 'burgers',
    image: '/uploads/menu/b8.jpg',
    rating: 4.7,
    prepTime: 14,
  },
  {
    id: 'b9',
    name: 'Capture Double Patty',
    description: 'Beef smash Bar B.Q grilled, cheese with cocktail sauce.',
    price: 749,
    category: 'burgers',
    image: '/uploads/menu/b9.jpg',
    rating: 4.8,
    prepTime: 16,
  },
  {
    id: 'b10',
    name: 'Smokiya',
    description: 'Buttered bun, chicken Thai steak, cheese with chipotle sauce.',
    price: 699,
    category: 'burgers',
    image: '/uploads/menu/b10.jpg',
    rating: 4.7,
    prepTime: 14,
  },
  {
    id: 'b11',
    name: 'Chicken Smash 2 Patty',
    description: 'Buttered bun, chicken smash patty with regular sauce.',
    price: 449,
    category: 'burgers',
    image: '/uploads/menu/b11.jpg',
    rating: 4.6,
    prepTime: 12,
  },
  // ARABIAN
  {
    id: 'a1',
    name: 'Khubs Al Laham Signature',
    description: 'Baik beef with Lubna sauce & Humas vinegar veges.',
    price: 899,
    category: 'arabian',
    image: '/uploads/menu/a1.jpg',
    rating: 4.8,
    prepTime: 15,
  },
  {
    id: 'a2',
    name: 'Khubs Al Dajaj Signature',
    description: 'Baik chicken with Lubna sauce & Humas vinegar veges.',
    price: 899,
    category: 'arabian',
    image: '/uploads/menu/a2.jpg',
    rating: 4.8,
    prepTime: 15,
  },
  {
    id: 'a3',
    name: 'Laham Batatus',
    description: 'Loaded fries with buffalo chunks, cheese & signature sauce.',
    price: 599,
    category: 'arabian',
    image: '/uploads/menu/a3.jpg',
    rating: 4.7,
    prepTime: 12,
  },
  {
    id: 'a4',
    name: 'Laham Mandi Signature',
    description: 'Buffalo meat with smoky rice & Zaltahar sauce Zaltabarit.',
    price: 999,
    category: 'arabian',
    image: '/uploads/menu/a4.jpg',
    rating: 4.9,
    prepTime: 22,
  },
  {
    id: 'a5',
    name: 'Kabsa Dajaj',
    description: 'Chicken pieces, white sauce with cheese & signature sauce.',
    price: 799,
    category: 'arabian',
    image: '/uploads/menu/a5.jpg',
    rating: 4.8,
    prepTime: 18,
  },
  {
    id: 'a6',
    name: 'Baik Al Batatus',
    description: 'Loaded fries with crispy chicken, cheese & signature sauce.',
    price: 499,
    category: 'arabian',
    image: '/uploads/menu/a6.jpg',
    rating: 4.6,
    prepTime: 10,
  },
  // CHINESE
  {
    id: 'c1',
    name: 'Chicken Chilli Dry',
    description: 'With egg fried rice.',
    price: 859,
    category: 'chinese',
    image: '/uploads/menu/c1.jpg',
    rating: 4.7,
    prepTime: 16,
  },
  {
    id: 'c2',
    name: 'Beef Chilli',
    description: 'With egg fried rice.',
    price: 999,
    category: 'chinese',
    image: '/uploads/menu/c2.jpg',
    rating: 4.8,
    prepTime: 18,
  },
  // FRIED
  {
    id: 'f1',
    name: 'Chicken Fried Super Classic - 4pcs',
    description: 'Chicken pieces fully loaded with signature sauce.',
    price: 999,
    category: 'fried',
    image: '/uploads/menu/f1.jpg',
    rating: 4.8,
    prepTime: 15,
  },
  {
    id: 'f2',
    name: 'Chicken Fried Super Classic - 9pcs',
    description: 'Chicken pieces fully loaded with signature sauce.',
    price: 1899,
    category: 'fried',
    image: '/uploads/menu/f2.jpg',
    rating: 4.8,
    prepTime: 20,
  },
  {
    id: 'f3',
    name: 'Crispy Chicken Tender - 5pcs',
    description: 'Crispy chicken tenders with signature sauce.',
    price: 999,
    category: 'fried',
    image: '/uploads/menu/f3.jpg',
    rating: 4.7,
    prepTime: 12,
  },
  {
    id: 'f4',
    name: 'Crispy Chicken Tender - 10pcs',
    description: 'Crispy chicken tenders with signature sauce.',
    price: 1899,
    category: 'fried',
    image: '/uploads/menu/f4.jpg',
    rating: 4.7,
    prepTime: 18,
  },
  {
    id: 'f5',
    name: 'Funky Wings - 6pcs',
    description: 'Crispy wings sesame with signature sauce.',
    price: 599,
    category: 'fried',
    image: '/uploads/menu/f5.jpg',
    rating: 4.7,
    prepTime: 10,
  },
  {
    id: 'f6',
    name: 'Funky Wings - 12pcs',
    description: 'Crispy wings sesame with signature sauce.',
    price: 1099,
    category: 'fried',
    image: '/uploads/menu/f6.jpg',
    rating: 4.7,
    prepTime: 15,
  },
  {
    id: 'f7',
    name: 'Cheesy Stuff Rolat - 6pcs',
    description: 'Chicken cheese stuff with butter mushroom sauce.',
    price: 599,
    category: 'fried',
    image: '/uploads/menu/f7.jpg',
    rating: 4.8,
    prepTime: 12,
  },
  {
    id: 'f8',
    name: 'Cheesy Stuff Rolat - 12pcs',
    description: 'Chicken cheese stuff with butter mushroom sauce.',
    price: 1199,
    category: 'fried',
    image: '/uploads/menu/f8.jpg',
    rating: 4.8,
    prepTime: 18,
  },
  {
    id: 'f9',
    name: 'Niblets Wings - 6pcs',
    description: 'Crispy wings sesame sweet & chilli Thai sauce.',
    price: 499,
    category: 'fried',
    image: '/uploads/menu/f9.jpg',
    rating: 4.6,
    prepTime: 10,
  },
  {
    id: 'f10',
    name: 'Niblets Wings - 12pcs',
    description: 'Crispy wings sesame sweet & chilli Thai sauce.',
    price: 799,
    category: 'fried',
    image: '/uploads/menu/f10.jpg',
    rating: 4.6,
    prepTime: 14,
  },
  // PASTA
  {
    id: 'p1',
    name: 'Special Pasta Signature',
    description: 'Grilled chicken pasta mushroom jalapeno with signature sauce.',
    price: 799,
    category: 'pasta',
    image: '/uploads/menu/p1.jpg',
    rating: 4.8,
    prepTime: 16,
  },
  {
    id: 'p2',
    name: 'Lazania Signature - Large',
    description: 'Chicken chunks cheese with white sauce.',
    price: 799,
    category: 'pasta',
    image: '/uploads/menu/p2.jpg',
    rating: 4.8,
    prepTime: 18,
  },
  {
    id: 'p3',
    name: 'Lazania Signature - XL',
    description: 'Chicken chunks cheese with white sauce.',
    price: 1199,
    category: 'pasta',
    image: '/uploads/menu/p3.jpg',
    rating: 4.8,
    prepTime: 22,
  },
  {
    id: 'p4',
    name: 'Alfredo Signature - Buffalo',
    description: 'Grilled steak pasta with funky sauce.',
    price: 1049,
    category: 'pasta',
    image: '/uploads/menu/p4.jpg',
    rating: 4.9,
    prepTime: 18,
  },
  {
    id: 'p5',
    name: 'Alfredo Signature - Chicken',
    description: 'Grilled chicken pasta with funky sauce.',
    price: 749,
    category: 'pasta',
    image: '/uploads/menu/p5.jpg',
    rating: 4.8,
    prepTime: 16,
  },
  {
    id: 'p6',
    name: 'Chowmein',
    description: 'Smoky chicken grilled veges & chilli sauce.',
    price: 799,
    category: 'pasta',
    image: '/uploads/menu/p6.jpg',
    rating: 4.7,
    prepTime: 14,
  },
];

export function getFoodById(id: string): FoodItem | undefined {
  return MENU_ITEMS.find((item) => item.id === id);
}
